config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :analytics

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 1, maximum: 100 }
end

app/models/query.rb
class Query < ApplicationRecord
    validates :search_query, presence: true
  
    def process!
      if query_already_searched? && !candidate_for_update?
        duplicate_query.increment!(:views_count) 
      else
        candidate_for_update? ? latest_query.update!(search_query: search_query) : save!
      end
    end

    private

    def latest_query
      @latest_query ||= self.class.where(ip_address: ip_address).last
    end

    def duplicate_query
      @duplicate_query ||= self.class.find_by(ip_address: ip_address, search_query: search_query)
    end

    def candidate_for_update?
      return false unless latest_query
      return true if in_search_session? && search_query.include?(latest_query.search_query)

      return false
    end

    def in_search_session?
      latest_query.updated_at > 15.seconds.ago
    end

    def query_already_searched?
      return false unless duplicate_query 
      return true if !in_search_session?
      return true if !search_query.include?(latest_query.search_query) && in_search_session?
 
      false
    end
  end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
    def index
      @user_queries = Query.where(ip_address: request.remote_ip)
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: %i[ show edit update destroy ]
  
    def index
      query = params[:query].to_s.strip
  
      if query.present?
        @posts = Post.where("LOWER(title) LIKE ?", "%#{query.downcase}%")

        Query.new(
          search_query: query,
          ip_address: request.remote_ip,
          views_count: 1
        ).process!
      else
        @posts = Post.all
      end
  
      if turbo_frame_request?
        render partial: "posts", locals: { posts: @posts }
      else
        render :index
      end
    end
  
    def show
      @post = Post.find(params[:id])
    end
  
    def new
      @post = Post.new
    end
  
    def edit
    end
  
    def create
      @post = Post.new(post_params)
  
      respond_to do |format|
        if @post.save
          format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      @post.destroy
  
      respond_to do |format|
        format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
        format.json { head :no_content }
      end
    end
    
    
    private
    
      def set_post
        @post = Post.find(params[:id])
      end
  
      def post_params
        params.require(:post).permit(:title, :body)
      end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/analytics/index.html.erb
<div class="analytics-container">

<table>
  <thead>
    <tr>
      <th>Search Query</th>
      <th>View Count</th>
    </tr>
  </thead>
  <tbody>
    <% @user_queries.each do |query| %>
      <tr>
        <td><%= query.search_query %></td>
        <td><%= query.views_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchAnalyticsRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
    <%= render 'shared/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, html: { class: 'post-form' }) do |form| %>
  <% if post.errors.any? %>
    <div class="error">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title, class: 'input-field' %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body, class: 'textarea-field' %>
  </div>

  <div>
    <%= form.submit 'Save', class: 'submit-btn' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post" id="<%= dom_id post %>">
   <h1 class="post-title"><%= post.title %></h1>
   <p class="post-body"><%= post.body %></p>
</div>

app/views/posts/_posts.html.erb
<turbo-frame id="posts" class="posts-frame">
  <% @posts.each do |post| %>
    <%= link_to post_path(post), class: 'post-link', data: { turbo: "false" } do %>
      <div class="post-item" id="<%= dom_id(post) %>">
        <p class="post-title">
          <%= post.title %>
        </p>
        <p class="post-body">
          <%= truncate(post.body, length: 200, separator: '.').to_s + '...' %>
        </p>
      </div>
    <% end %>
  <% end %>
</turbo-frame>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div class="button-container" >
  <%= link_to "Back to posts", posts_path, class: 'button back-button'%>
  <%= link_to "Show this post", @post, class: 'button show-button' %> 
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

  
  <%= form_with(url: posts_path, method: :get, data: {controller: "search-form", turbo_frame: "posts", turbo_action: "advance"}, html: { class: "search-form" }) do |form| %>
    <div class="search-container">
      <div class="search-input">
        <%= form.text_field :query, class: "search-text-field", data: { action: "input->search-form#search" } %>
        <%= form.submit 'Search', class: "search-submit-btn" %>
      </div>
    </div>
  <% end %>
 

<div class="posts-container">
  <%= render "posts", posts: @posts %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p class="notice-message"><%= notice %></p>

<%= render @post %>

<div class="button-container">
  <%= link_to "Back to posts", posts_path, class: 'button back-button' %>
  <%= link_to "Edit this post", edit_post_path(@post), class: 'button edit-button' %>
  <%= button_to "Destroy this post", @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button destroy-button' %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <ul class="navbar-list">
    <li class="navbar-item"><%= link_to 'Home', root_path, class: 'navbar-link' %></li>
    <li class="navbar-item"><%= link_to "Analytics", analytics_path, class: 'navbar-link' %></li>
    <li class="navbar-item"> <%= link_to "New post", new_post_path, class: "button new-button" %> </li>
  </ul>
</nav>